eyeChar = input("Please enter a character for the eye")
print("Beep's expression is now as follows:")

print("\t##########")
print("\t# ", eyeChar,"",eyeChar," #")
print("\t#  ____  #")
print("\t##########")
print(" ################")
print(" #  ##########  #")
print(" #  ##########  #")
print("    ##########")
print("     ########")